bandmaker2/accounts/urls.py
# coding:utf-8
from django.conf.urls import url,include
from . import views

app_name='accounts'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^regist/$',views.regist,name='regist'),
    url(r'^regist_confirm/$',views.regist_confirm,name='regist_confirm'),
    url(r'^regist_save/$',views.regist_save,name='regist_save'),
]

bandmaker2/bandmaker2/urls.py
# coding:utf-8
"""bandmaker2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'mypage/',include('mypage.urls')),
]

bandmaker2/mypage/urls.py
# coding:utf-8
from django.conf.urls import url,include
from . import views
app_name = 'mypage'

urlpatterns=[
    url(r'^$',views.index,name='index'),
    url(r'^edit/$',views.edit,name='edit'),
    url(r'^edit_confirm/$',views.edit_confirm,name='edit_confirm'),
    url(r'^edit_save/$',views.edit_save,name='edit_save'),
]

bandmaker2/accounts/models.py
# coding:utf-8
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from mypage.models import Profile
# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, email,first_name,last_name,profile_id,password = None,**extra_fields):
        if not email:
            raise ValueError('Users must have a email address')
        if not first_name:
            raise ValueError('User must have a first_name')
        if not last_name:
            raise ValueError('User must have a last_name')
        email = MyUserManager.normalize_email(email)
        user = self.model(email = email,first_name = first_name,last_name=last_name,profile_id=profile_id,**extra_fields)
        user.set_password(password)
        user.save(using = self._db)
        return user
    def create_superuser(self,email,first_name,last_name,password):
        return self.create_user(email,first_name,last_name,password)

class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=128,unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    profile_id = models.ForeignKey(Profile,on_delete=models.CASCADE,)
    is_active = models.BooleanField(default=True)
    USERNAME_FIELD = 'email'
    objects = MyUserManager()
    # class Meta:
        # swappable = 'AUTH_USER_MODEL'
    def validate_unique(self, exclude=None):
        """Validate the field uniqueness"""
        MyUser.objects.filter(email=self.email, is_active=False).delete()
        super(MyUser, self).validate_unique(exclude)

bandmaker2/mypage/models.py
# coding:utf-8
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    nickname = models.CharField(max_length=50,blank=True,default="")
    favorite_musician = models.TextField(max_length=300,blank=True,default="")
    my_inst = models.TextField(max_length=300,blank=True,default="")

bandmaker2/next/models.py
# coding:utf-8
from django.db import models

# Create your models here.

bandmaker2/accounts/forms.py
# coding:utf-8
from django import forms
from accounts.models import MyUser

class UserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation',widget=forms.PasswordInput)
    class Meta:
        model = MyUser
        fields = ('email','first_name','last_name',)
    def clean_password2(self):
        # バリデーション済のデータを取得
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        # password1とpassword2が一致するかチェック
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2
    # save
    def save(self, commit=True):
        
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

bandmaker2/mypage/forms.py
# coding:utf-8
from django.forms import ModelForm
from .models import Profile
from django.contrib.auth.models import User

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

bandmaker2/accounts/views.py
# coding:utf-8
from django.shortcuts import render,redirect
from django.views.decorators.http import require_POST
from .forms import UserForm 
from django.contrib.auth import login
from mypage.forms import ProfileForm
def index(request):
    
    return render(request,'accounts/index.html')
# Create your views here.
def regist(request):
    # バリデーション失敗時のページ到着も考慮してデータを取得
    form_data = request.session.pop('form_data',None)
    form = UserForm(form_data)
    context ={
        "form":form,
    }
    return render(request,'accounts/regist.html',context)
@require_POST
def regist_confirm(request):
    # 受け取ったrequestのPOSTのデータを取得
    form = UserForm(request.POST)
    context = {
        "form":form,
    }
    # バリデーションでうまく行けば確認画面を表示
    if form.is_valid():
        #フォームデータをセッションに保存
        request.session['form_data']=request.POST
        return render(request,'accounts/regist_confirm.html',context)
    # バリデーション失敗時にはフォームに戻る
    return render(request,'accounts/regist.html',context)

@require_POST
def regist_save(request):
    form_data = request.session.pop('form_data',None)
    form = UserForm(form_data)
    if form.is_valid():
        user = form.save(commit=False)
        profile = ProfileForm(commit = False)
        profile.save()
        user.profile_id = profile.id
        user.save()
        login(request,user,backend="django.contrib.auth.backends.ModelBackend")
        return redirect("accounts:index")
    context = {
        "form":form,
    }
    return render(request,'accounts/regist_confirm',context)
        

bandmaker2/mypage/views.py
# coding:utf-8
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.generic.list import ListView
from django.utils import timezone
from django.contrib.auth.models import User
from mypage.models import Profile 
from .forms import ProfileForm

# Create your views here.
@login_required
def index(request):
    # idからユーザ検索
    # ユーザからProfileを検索
    profile = Profile.objects.filter(id = request.user.profile_id)
    context={
        'form':profile,
    }
    return render(request,'mypage/index.html',context)
@login_required
def edit(request):
    # sessionにデータがあれば取得
    form_data = request.session.pop('profile_data',None)
    # sessionからデータを取得できればフォームに入力
    form = ProfileForm(form_data)
    context = {
        "form":form
    }
    return render(request,'mypage/edit.html',context)

@login_required
@require_POST
def edit_confirm(request):
    form = ProfileForm(request.POST)
    context = {
        "form":form,
    }    
    if form.is_valid():
        request.session["profile_data"] = request.POST
        return render(request,'mypage/edit_confirm.html',context)
    return render(request,'mypage/edit.html',context)
@login_required
@require_POST
def edit_save(request):
    # フォームデータをセッションから取得
    form_data = request.session.pop('profile_data',None)
    form = ProfileForm(form_data)
    if form.is_valid():
        profile = form.save(commit=False)
        profile.save()
        return redirect("mypage:index")
    context = {
        "form":form
    }
    return render(request,'mypage/edit_confirm',context)

    
    
    

bandmaker2/next/views.py
# coding:utf-8
from django.shortcuts import render

# Create your views here.

bandmaker2/accounts/templates/accounts/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>accounts</title>

</head>

<body>
    {% block content %} {% endblock %}
</body>

</html>

bandmaker2/accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %} {% block content %}
<h1>
    {% if user.is_authenticated %} ユーザ名:{{ user.username}}<br> {% else %} ようこそゲスト {% endif %}
</h1>
<hr>
<a href="{% url 'accounts:regist' %}">ユーザ作成</a> {% endblock %}

bandmaker2/accounts/templates/accounts/regist.html
{% extends 'accounts/base.html' %} {% block content %}
<p>こんにちわ</p>
<form action="{% url 'accounts:regist_confirm' %}" method="POST">
    {{form.as_p}}{% csrf_token %}
    <input type="submit" value="登録">
</form>
{% endblock %}

bandmaker2/accounts/templates/accounts/regist_confirm.html
{% extends 'accounts/base.html' %} {% block content %} {% for field in form %}{{field.label_tag}}{{field.value}}
<br> {% endfor %}
<form action="{% url 'accounts:regist_save' %}" method="POST">
    <input type="submit" value="送信"> {% csrf_token %}
</form>
<a href="{% url 'accounts:regist' %}">戻る</a> {% endblock %}

bandmaker2/mypage/templates/mypage/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <title>mypage</title>

</head>

<body>
    {% block content %} {% endblock %}
</body>

</html>

bandmaker2/mypage/templates/mypage/edit.html
{% extends 'mypage/base.html' %} {% block content %}
<p>プロフィール編集</p>
<form action="{% url 'mypage:edit_confirm'%}" method="POST">
    {{form.as_p}}{% csrf_token %}
    <input type="submit" value="登録">
</form>
{% endblock %}

bandmaker2/mypage/templates/mypage/edit_confirm.html
{% extends 'mypage/base.html'%}{% block content%} {% for field in form %}{{field.label_tag}}{{field.value}}
<br>{% endfor%}
<form action="{% url 'mypage:edit_save'%}" method="POST">
    <input type="submit" value="送信">{% csrf_token %}
</form>
<a href="{% url 'mypage:edit'%}">戻る</a>{% endblock %}

bandmaker2/mypage/templates/mypage/index.html
{% extends 'mypage/base.html' %} {% block content %} {{ form.nickname}} {% endblock %}